import type { ProjectData, Task } from './schema.js';

export function renderProgressBar(percentage: number, length: number = 20): string {
  const clamped = Math.max(0, Math.min(100, Math.round(percentage)));
  const filled = Math.round((clamped / 100) * length);
  const empty = length - filled;
  return `[${'█'.repeat(filled)}${'░'.repeat(empty)}] ${clamped}%`;
}

export function generateMarkdownOverview(data: ProjectData): string {
  const { meta, features, tasks, flows } = data;
  const totalTasks = tasks.length;
  const completedTasks = tasks.filter(t => t.status === 'done').length;
  const inProgressTasks = tasks.filter(t => t.status === 'in_progress').length;
  const todoTasks = tasks.filter(t => t.status === 'todo').length;

  const bar = renderProgressBar(meta.overallProgress, 24);

  let md = `# ${meta.name} — Project Overview\n\n`;
  md += `> ${meta.description}\n\n`;

  md += `### Live Progress\n`;
  md += `\`\`\`text\n${bar}\n`;
  md += `Total Tasks: ${totalTasks} | Done: ${completedTasks} | In Progress: ${inProgressTasks} | Pending: ${todoTasks}\n`;
  md += `\`\`\`\n\n`;

  md += `| Attribute | Details |\n`;
  md += `| :--- | :--- |\n`;
  md += `| **Project Type** | \`${meta.projectType}\` |\n`;
  md += `| **Frameworks / Stack** | ${meta.frameworks.map(f => `\`${f}\``).join(', ') || 'Not specified'} |\n`;
  md += `| **Version** | \`v${meta.version}\` |\n`;
  md += `| **Last Updated** | ${new Date(meta.updatedAt).toLocaleString()} |\n`;
  md += `| **Interactive Dashboard** | Run \`npx what-is-it\` to view full visual UI & Wiki |\n\n`;

  md += `## Features & Status\n\n`;
  md += `| Feature | Status | Progress | Tasks Done |\n`;
  md += `| :--- | :--- | :--- | :--- |\n`;
  for (const f of features) {
    const fTasks = tasks.filter(t => t.featureId === f.id);
    const fDone = fTasks.filter(t => t.status === 'done').length;
    const statusIcon = f.status === 'completed' ? '✅ Completed' : f.status === 'in_progress' ? '🟡 In Progress' : '⚪ Planned';
    md += `| **${f.title}** | ${statusIcon} | \`${f.progress}%\` | ${fDone}/${fTasks.length} |\n`;
  }
  md += `\n`;

  // Active / in-progress tasks
  const activeTasks = tasks.filter(t => t.status === 'in_progress' || (t.status === 'todo' && t.priority === 'urgent'));
  if (activeTasks.length > 0) {
    md += `## Current Focus (Active & Urgent Tasks)\n\n`;
    for (const t of activeTasks) {
      const icon = t.status === 'in_progress' ? '⚡' : '🔥';
      md += `### ${icon} ${t.title} (\`${t.id}\`)\n`;
      md += `- **Why**: ${t.why}\n`;
      md += `- **Where**: \`${t.where}\`\n`;
      md += `- **How**: ${t.how}\n`;
      md += `- **When**: ${t.when}\n\n`;
    }
  }

  // Visual User Flows summary
  if (flows.length > 0) {
    md += `## Visual User Flows (${flows.length})\n\n`;
    for (const flow of flows) {
      md += `- **${flow.title}** (Role: \`${flow.actorRole}\`): ${flow.description} — *${flow.nodes.length} screen nodes mapped in interactive graph*\n`;
    }
    md += `\n`;
  }

  md += `---\n\n`;
  md += `### How to use with Agents & Humans\n`;
  md += `- **For Humans**: Run \`npx what-is-it\` in your terminal to launch the interactive UI dashboard, right-rail wiki, and SVG React Flow graph.\n`;
  md += `- **For Agents**: Check status via \`npx what-is-it status\`. When completing tasks, execute \`npx what-is-it task done <task-id>\`.\n`;
  md += `\n*Auto-generated by \`what-is-it\` live memory system.*\n`;

  return md;
}
